### ISSUE TITLE
2.3.1 - Puppet lint fails with 1.8.7-p371 and Puppet 3.8.0

### ISSUE THREAD

**Issue by jeffmccune** [rodjek/puppet-lint#759]
Expected behavior: Same as 2.3.0

Actual behavior:

```
SyntaxError: /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/configuration.rb:53: undefined (?...) sequence: /^(?<option>\w+)=?$/
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint.rb:7:in `gem_original_require'
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint.rb:7:in `require'
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint.rb:7
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/tasks/puppet-lint.rb:1:in `gem_original_require'
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/tasks/puppet-lint.rb:1:in `require'
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/tasks/puppet-lint.rb:1
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppetlabs_spec_helper-2.0.2/lib/puppetlabs_spec_helper/rake_tasks.rb:438:in `gem_original_require'
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppetlabs_spec_helper-2.0.2/lib/puppetlabs_spec_helper/rake_tasks.rb:438:in `require'
/home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppetlabs_spec_helper-2.0.2/lib/puppetlabs_spec_helper/rake_tasks.rb:438
/home/travis/build/acme/puppet-module-confluence/Rakefile:1:in `gem_original_require'
/home/travis/build/acme/puppet-module-confluence/Rakefile:1:in `require'
/home/travis/build/acme/puppet-module-confluence/Rakefile:1
/home/travis/.rvm/gems/ruby-1.8.7-p371/bin/ruby_executable_hooks:15
(See full trace by running task with --trace)
```

Using a module with a build matrix of:

```
---
language: ruby

rvm:
  - 1.8.7
  - 2.1.9

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.8.0"
    - PUPPET_GEM_VERSION="~> 4"

sudo: false

# TODO: add spec tests
script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint'

matrix:
  fast_finish: true
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 3.8.0"

notifications:
  email: false
```
